
export const MOVIES_NOW_PLAYING_FETCH_START = 'MOVIES_NOW_PLAYING_FETCH_START';

export const MOVIES_NOW_PLAYING_FETCH_SUCCESS = 'MOVIES_NOW_PLAYING_FETCH_SUCCESS';

export const MOVIES_NOW_PLAYING_FETCH_FAIL = 'MOVIES_NOW_PLAYING_FETCH_FAIL';

export const MOVIES_NOW_PLAYING_RESET = 'MOVIES_NOW_PLAYING_RESET';
